### ISSUE TITLE
Gnome

### ISSUE THREAD

**Issue by alecandido** [alecandido/nixpkgs#27]
Tweak Gnome.

- [ ] `/org/gnome/shell` in dconf
```toml
[/]
app-picker-layout=[{'org.gnome.clocks.desktop': <{'position': <0>}>, 'org.gnome.Calendar.desktop': <{'position': <1>}>, 'org.gnome.Loupe.desktop': <{'position': <2>}>, 'org.gnome.Totem.desktop': <{'position': <3>}>, 'org.gnome.Music.desktop': <{'position': <4>}>, 'org.gnome.Snapshot.desktop': <{'position': <5>}>, 'org.gnome.Settings.desktop': <{'position': <6>}>, 'Utilities': <{'position': <7>}>, 'org.gnome.Evince.desktop': <{'position': <8>}>, 'org.gnome.TextEditor.desktop': <{'position': <9>}>, 'gnome-system-monitor.desktop': <{'position': <10>}>, 'org.gnome.Weather.desktop': <{'position': <11>}>, 'org.gnome.Maps.desktop': <{'position': <12>}>, 'org.gnome.Calculator.desktop': <{'position': <13>}>, 'com.mattjakeman.ExtensionManager.desktop': <{'position': <14>}>, 'org.gnome.Extensions.desktop': <{'position': <15>}>, 'org.gnome.Contacts.desktop': <{'position': <16>}>, 'simple-scan.desktop': <{'position': <17>}>, 'org.gnome.Epiphany.desktop': <{'position': <18>}>, 'org.gnome.Fractal.desktop': <{'position': <19>}>, 'org.gnome.Geary.desktop': <{'position': <20>}>, 'yelp.desktop': <{'position': <21>}>, 'org.gnome.Tour.desktop': <{'position': <22>}>}, {'nixos-manual.desktop': <{'position': <0>}>, 'brave-browser.desktop': <{'position': <1>}>, 'org.telegram.desktop.desktop': <{'position': <2>}>, 'thunderbird.desktop': <{'position': <3>}>, 'nvim.desktop': <{'position': <4>}>, 'htop.desktop': <{'position': <5>}>, 'btop.desktop': <{'position': <6>}>, 'cups.desktop': <{'position': <7>}>, 'kitty.desktop': <{'position': <8>}>, 'xterm.desktop': <{'position': <9>}>}]
enabled-extensions=['appindicatorsupport@rgcjonas.gmail.com']
favorite-apps=['firefox.desktop', 'org.gnome.Nautilus.desktop']

[app-switcher]
current-workspace-only=true
```
